language: go

go:
  - 1.14

before_install:
  - sudo apt-get update
  - sudo apt-get install -y snapd
  - sudo snap install docker
script: 
  - docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test